### ISSUE TITLE
Club details.

### ISSUE THREAD

**Issue by DoubleBond** [Earthii/LastCallMTL-Project#12]
https://files.gitter.im/Earthii/LastCallMTL-Project/Cos5/thumb/blob.png

Currently, the modals look like that. I want that every club modal to be styled exactly like below. First showing an interactive google map shown like below, and every other slide, pictures of the club. To be done and revised in the club-details branch. Any questions?

https://files.gitter.im/Earthii/LastCallMTL-Project/3f9N/thumb/club-details.jpg

**Comment by Earthii** [comment]
Do you want the map to be black and white?

**Comment by DoubleBond** [comment]
Yes sir, https://snazzymaps.com/style/15/subtle-grayscale.
https://snazzymaps.com/about
Do we want a slider?

**Comment by DoubleBond** [comment]
Michel mentioned adding prices in the modal too. Would the modal contain an approximate price range? Do you think we should have a separate page (pricings) for that or contain in both pages?
